#!/usr/bin/python3
#-*- coding: utf-8 -*-

###########
# Imports #
###########

import discord
from discord.ext import commands
import youtube_dl

########
# Code #
########

youtube_dl.utils.bug_reports_message = lambda: ''

ytdl_format_options = {
    'format': 'bestaudio/best',
    'outtmpl': '%(extractor)s-%(id)s-%(title)s.%(ext)s',
    'restrictfilenames': True,
    'noplaylist': True,
    'nocheckcertificate': True,
    'ignoreerrors': False,
    'logtostderr': False,
    'quiet': True,
    'no_warnings': True,
    'default_search': 'auto',
    'source_address': '0.0.0.0'
}

ytdl = youtube_dl.YoutubeDL(ytdl_format_options)

class Music:

    def __init__(self, bot):
        self.bot = bot

    @commands.command(usage="play link")
    async def play(self, ctx, link):
        vc = await ctx.message.author.voice.channel.connect()


def setup(bot):
    bot.add_cog(Music(bot))